# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get NPM tag
        id: npm_tag
        run: echo "current_version=$(cat packages/trackutil/package.json | grep "version" | head -1 | cut -d '"' -f4)" >> $GITHUB_OUTPUT

      - name: Check if tags match
        if: ${{ github.ref_name != steps.npm_tag.outputs.current_version }}
        run: echo "GIT ${{ github.ref_name }} != NPM ${{ steps.npm_tag.outputs.current_version }}" && exit 1

      - uses: voidzero-dev/setup-vp@v1
        with:
          working-directory: ./packages/trackutil
          node-version: '24'
          cache: true

      - run: vp install
      - run: vp check
      - run: vp test

      - name: Build library
        working-directory: ./packages/trackutil
        run: vp pack

      - name: Publish library to NPM
        working-directory: ./packages/trackutil
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

      - name: Build webapp
        working-directory: ./apps/website
        run: vp build

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/website/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
